autoload:
  plugins_application_ipf_lib:
    name:           plugins_application_ipf_lib
    path:           %SF_PLUGINS_DIR%/ipfWebAppFrameworkPlugin/lib
    recursive:      true

#  plugins_application_module_lib:
#    name:           plugins application module lib
#    path:           %SF_PLUGINS_DIR%/*/apps/*/modules/*/lib
#    recursive:      true
