# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sfSmartyView:
    class_path: /usr/local/hdp/php/Smarty-3.1.13/libs
    template_extension: .tpl
    template_secutrity: true
  sfSmarty:
    class_path: ../../php/Smarty-3.1.13/libs
    template_extension: .tpl
    template_secutrity: true
